// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WalletRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface WalletRoot : GPBRootObject
@end

#pragma mark - RequestWalletInfo

typedef GPB_ENUM(RequestWalletInfo_FieldNumber) {
  RequestWalletInfo_FieldNumber_CheckSum = 1,
  RequestWalletInfo_FieldNumber_Payload = 2,
  RequestWalletInfo_FieldNumber_Salt = 3,
  RequestWalletInfo_FieldNumber_N = 4,
  RequestWalletInfo_FieldNumber_Wid = 5,
  RequestWalletInfo_FieldNumber_Version = 6,
};

/**
 * 新的钱包
 **/
@interface RequestWalletInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *checkSum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite) int32_t n;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wid;

@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - RequestUserInfo

typedef GPB_ENUM(RequestUserInfo_FieldNumber) {
  RequestUserInfo_FieldNumber_Uid = 1,
};

@interface RequestUserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
