// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Coin;
@class CoinInfo;
@class OriginalTransaction;
@class SpentCurrency;
@class TransactionFlowing;
@class Txin;
@class Txout;
@class Wallet;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WalletRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface WalletRoot : GPBRootObject
@end

#pragma mark - RequestWalletInfo

typedef GPB_ENUM(RequestWalletInfo_FieldNumber) {
  RequestWalletInfo_FieldNumber_Payload = 1,
  RequestWalletInfo_FieldNumber_Pbkdf2Iterations = 2,
  RequestWalletInfo_FieldNumber_CheckSum = 3,
  RequestWalletInfo_FieldNumber_Version = 4,
};

/**
 * 新的钱包
 **/
@interface RequestWalletInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite) int32_t pbkdf2Iterations;

@property(nonatomic, readwrite, copy, null_resettable) NSString *checkSum;

@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - RespSyncWallet

typedef GPB_ENUM(RespSyncWallet_FieldNumber) {
  RespSyncWallet_FieldNumber_Wallet = 1,
  RespSyncWallet_FieldNumber_Status = 2,
  RespSyncWallet_FieldNumber_CoinsArray = 3,
};

@interface RespSyncWallet : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Wallet *wallet;
/** Test to see if @c wallet has been set. */
@property(nonatomic, readwrite) BOOL hasWallet;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Coin*> *coinsArray;
/** The number of items in @c coinsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger coinsArray_Count;

@end

#pragma mark - Wallet

typedef GPB_ENUM(Wallet_FieldNumber) {
  Wallet_FieldNumber_PayLoad = 1,
  Wallet_FieldNumber_Version = 2,
  Wallet_FieldNumber_Pbkdf2Iterations = 3,
  Wallet_FieldNumber_CheckSum = 4,
};

@interface Wallet : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *payLoad;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t pbkdf2Iterations;

@property(nonatomic, readwrite, copy, null_resettable) NSString *checkSum;

@end

#pragma mark - Balance

typedef GPB_ENUM(Balance_FieldNumber) {
  Balance_FieldNumber_Amount = 1,
  Balance_FieldNumber_Pending = 2,
};

@interface Balance : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t pending;

@end

#pragma mark - Coin

typedef GPB_ENUM(Coin_FieldNumber) {
  Coin_FieldNumber_Currency = 1,
  Coin_FieldNumber_Payload = 2,
  Coin_FieldNumber_Salt = 3,
  Coin_FieldNumber_Balance = 4,
  Coin_FieldNumber_Status = 5,
  Coin_FieldNumber_Category = 6,
};

@interface Coin : GPBMessage

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) int32_t category;

@end

#pragma mark - Coins

typedef GPB_ENUM(Coins_FieldNumber) {
  Coins_FieldNumber_CoinsArray = 1,
};

@interface Coins : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Coin*> *coinsArray;
/** The number of items in @c coinsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger coinsArray_Count;

@end

#pragma mark - CoinsDetail

typedef GPB_ENUM(CoinsDetail_FieldNumber) {
  CoinsDetail_FieldNumber_Coin = 1,
  CoinsDetail_FieldNumber_CoinInfosArray = 2,
};

@interface CoinsDetail : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Coin *coin;
/** Test to see if @c coin has been set. */
@property(nonatomic, readwrite) BOOL hasCoin;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CoinInfo*> *coinInfosArray;
/** The number of items in @c coinInfosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger coinInfosArray_Count;

@end

#pragma mark - CoinInfo

typedef GPB_ENUM(CoinInfo_FieldNumber) {
  CoinInfo_FieldNumber_Index = 1,
  CoinInfo_FieldNumber_Address = 2,
  CoinInfo_FieldNumber_Label = 3,
  CoinInfo_FieldNumber_Balance = 4,
  CoinInfo_FieldNumber_Status = 5,
};

@interface CoinInfo : GPBMessage

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite) int32_t status;

@end

#pragma mark - CreateCoinRequest

typedef GPB_ENUM(CreateCoinRequest_FieldNumber) {
  CreateCoinRequest_FieldNumber_Currency = 1,
  CreateCoinRequest_FieldNumber_MasterAddress = 2,
  CreateCoinRequest_FieldNumber_Salt = 3,
  CreateCoinRequest_FieldNumber_Payload = 4,
  CreateCoinRequest_FieldNumber_Category = 5,
};

@interface CreateCoinRequest : GPBMessage

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *masterAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite) int32_t category;

@end

#pragma mark - CreateCoinAccount

typedef GPB_ENUM(CreateCoinAccount_FieldNumber) {
  CreateCoinAccount_FieldNumber_Index = 1,
  CreateCoinAccount_FieldNumber_Address = 2,
  CreateCoinAccount_FieldNumber_Label = 3,
  CreateCoinAccount_FieldNumber_Status = 4,
  CreateCoinAccount_FieldNumber_Currency = 5,
};

@interface CreateCoinAccount : GPBMessage

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) int32_t currency;

@end

#pragma mark - Txin

typedef GPB_ENUM(Txin_FieldNumber) {
  Txin_FieldNumber_AddressesArray = 1,
};

@interface Txin : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *addressesArray;
/** The number of items in @c addressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addressesArray_Count;

@end

#pragma mark - Txout

typedef GPB_ENUM(Txout_FieldNumber) {
  Txout_FieldNumber_Address = 1,
  Txout_FieldNumber_Amount = 2,
};

@interface Txout : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite) int64_t amount;

@end

#pragma mark - SpentCurrency

typedef GPB_ENUM(SpentCurrency_FieldNumber) {
  SpentCurrency_FieldNumber_Currency = 1,
  SpentCurrency_FieldNumber_Txin = 2,
};

@interface SpentCurrency : GPBMessage

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite, strong, null_resettable) Txin *txin;
/** Test to see if @c txin has been set. */
@property(nonatomic, readwrite) BOOL hasTxin;

@end

#pragma mark - LuckyPackageRequest

typedef GPB_ENUM(LuckyPackageRequest_FieldNumber) {
  LuckyPackageRequest_FieldNumber_SpentCurrency = 1,
  LuckyPackageRequest_FieldNumber_ReciverIdentifier = 2,
  LuckyPackageRequest_FieldNumber_Typ = 3,
  LuckyPackageRequest_FieldNumber_Size = 4,
  LuckyPackageRequest_FieldNumber_Amount = 5,
  LuckyPackageRequest_FieldNumber_Fee = 6,
  LuckyPackageRequest_FieldNumber_Tips = 7,
};

@interface LuckyPackageRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpentCurrency *spentCurrency;
/** Test to see if @c spentCurrency has been set. */
@property(nonatomic, readwrite) BOOL hasSpentCurrency;

/** group id or user pubkey(address) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *reciverIdentifier;

/** privte group outer */
@property(nonatomic, readwrite) int32_t typ;

@property(nonatomic, readwrite) int32_t size;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t fee;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - URLTransferRequest

typedef GPB_ENUM(URLTransferRequest_FieldNumber) {
  URLTransferRequest_FieldNumber_SpentCurrency = 1,
  URLTransferRequest_FieldNumber_Amount = 2,
  URLTransferRequest_FieldNumber_Fee = 3,
};

@interface URLTransferRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpentCurrency *spentCurrency;
/** Test to see if @c spentCurrency has been set. */
@property(nonatomic, readwrite) BOOL hasSpentCurrency;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t fee;

@end

#pragma mark - TransferRequest

typedef GPB_ENUM(TransferRequest_FieldNumber) {
  TransferRequest_FieldNumber_SpentCurrency = 1,
  TransferRequest_FieldNumber_TxOutArray = 2,
  TransferRequest_FieldNumber_Fee = 3,
  TransferRequest_FieldNumber_Tips = 4,
};

@interface TransferRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpentCurrency *spentCurrency;
/** Test to see if @c spentCurrency has been set. */
@property(nonatomic, readwrite) BOOL hasSpentCurrency;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Txout*> *txOutArray;
/** The number of items in @c txOutArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger txOutArray_Count;

@property(nonatomic, readwrite) int64_t fee;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - CrowdfuningRequest

typedef GPB_ENUM(CrowdfuningRequest_FieldNumber) {
  CrowdfuningRequest_FieldNumber_Currency = 1,
  CrowdfuningRequest_FieldNumber_GroupIdentifier = 2,
  CrowdfuningRequest_FieldNumber_PerAmount = 3,
  CrowdfuningRequest_FieldNumber_Size = 4,
  CrowdfuningRequest_FieldNumber_Tips = 5,
};

@interface CrowdfuningRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *groupIdentifier;

@property(nonatomic, readwrite) int64_t perAmount;

@property(nonatomic, readwrite) int32_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - ReceiptRequest

typedef GPB_ENUM(ReceiptRequest_FieldNumber) {
  ReceiptRequest_FieldNumber_Currency = 1,
  ReceiptRequest_FieldNumber_Payer = 2,
  ReceiptRequest_FieldNumber_Amount = 3,
  ReceiptRequest_FieldNumber_Tips = 4,
};

@interface ReceiptRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

/** who need pay this receipt */
@property(nonatomic, readwrite, copy, null_resettable) NSString *payer;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - HashIdResp

typedef GPB_ENUM(HashIdResp_FieldNumber) {
  HashIdResp_FieldNumber_HashId = 1,
};

@interface HashIdResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@end

#pragma mark - Pay

typedef GPB_ENUM(Pay_FieldNumber) {
  Pay_FieldNumber_SpentCurrency = 1,
  Pay_FieldNumber_PayType = 2,
  Pay_FieldNumber_HashId = 3,
};

@interface Pay : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) SpentCurrency *spentCurrency;
/** Test to see if @c spentCurrency has been set. */
@property(nonatomic, readwrite) BOOL hasSpentCurrency;

@property(nonatomic, readwrite) int32_t payType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@end

#pragma mark - OriginalTransactionResponse

typedef GPB_ENUM(OriginalTransactionResponse_FieldNumber) {
  OriginalTransactionResponse_FieldNumber_Code = 1,
  OriginalTransactionResponse_FieldNumber_Data_p = 2,
  OriginalTransactionResponse_FieldNumber_Message = 3,
};

@interface OriginalTransactionResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, strong, null_resettable) OriginalTransaction *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - OriginalTransaction

typedef GPB_ENUM(OriginalTransaction_FieldNumber) {
  OriginalTransaction_FieldNumber_HashId = 1,
  OriginalTransaction_FieldNumber_Rawhex = 2,
  OriginalTransaction_FieldNumber_Vts = 3,
  OriginalTransaction_FieldNumber_Fee = 4,
  OriginalTransaction_FieldNumber_AddressesArray = 5,
};

@interface OriginalTransaction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rawhex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *vts;

@property(nonatomic, readwrite) int64_t fee;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *addressesArray;
/** The number of items in @c addressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addressesArray_Count;

@end

#pragma mark - PublishTransaction

typedef GPB_ENUM(PublishTransaction_FieldNumber) {
  PublishTransaction_FieldNumber_TransactionType = 1,
  PublishTransaction_FieldNumber_HashId = 2,
  PublishTransaction_FieldNumber_TxHex = 3,
};

@interface PublishTransaction : GPBMessage

@property(nonatomic, readwrite) int32_t transactionType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *txHex;

@end

#pragma mark - TransactionFlowingRequest

typedef GPB_ENUM(TransactionFlowingRequest_FieldNumber) {
  TransactionFlowingRequest_FieldNumber_Currency = 1,
  TransactionFlowingRequest_FieldNumber_Page = 2,
  TransactionFlowingRequest_FieldNumber_Size = 3,
};

@interface TransactionFlowingRequest : GPBMessage

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite) int32_t page;

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - TransactionFlowing

typedef GPB_ENUM(TransactionFlowing_FieldNumber) {
  TransactionFlowing_FieldNumber_Time = 1,
  TransactionFlowing_FieldNumber_Username = 2,
  TransactionFlowing_FieldNumber_Address = 3,
  TransactionFlowing_FieldNumber_Avatar = 4,
  TransactionFlowing_FieldNumber_Amount = 5,
  TransactionFlowing_FieldNumber_Txid = 6,
  TransactionFlowing_FieldNumber_Status = 7,
  TransactionFlowing_FieldNumber_Category = 8,
};

@interface TransactionFlowing : GPBMessage

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite, copy, null_resettable) NSString *txid;

/** confirm unconfirm */
@property(nonatomic, readwrite) int32_t status;

/** transfer luckypackage */
@property(nonatomic, readwrite) int32_t category;

@end

#pragma mark - TransactionFlowings

typedef GPB_ENUM(TransactionFlowings_FieldNumber) {
  TransactionFlowings_FieldNumber_TransactionHistoryArray = 2,
};

@interface TransactionFlowings : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionFlowing*> *transactionHistoryArray;
/** The number of items in @c transactionHistoryArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionHistoryArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
