// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Wallet.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - WalletRoot

@implementation WalletRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - WalletRoot_FileDescriptor

static GPBFileDescriptor *WalletRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"wallet"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - RequestWalletInfo

@implementation RequestWalletInfo

@dynamic checkSum;
@dynamic payload;
@dynamic salt;
@dynamic n;
@dynamic wid;
@dynamic version;

typedef struct RequestWalletInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t n;
  int32_t version;
  NSString *checkSum;
  NSString *payload;
  NSString *salt;
  NSString *wid;
} RequestWalletInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "checkSum",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_CheckSum,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, checkSum),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "payload",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_Payload,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, payload),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "salt",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_Salt,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, salt),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "n",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_N,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, n),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "wid",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_Wid,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, wid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = RequestWalletInfo_FieldNumber_Version,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(RequestWalletInfo__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RequestWalletInfo class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RequestWalletInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RequestUserInfo

@implementation RequestUserInfo

@dynamic uid;

typedef struct RequestUserInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *uid;
} RequestUserInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uid",
        .dataTypeSpecific.className = NULL,
        .number = RequestUserInfo_FieldNumber_Uid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RequestUserInfo__storage_, uid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RequestUserInfo class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RequestUserInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Address

@implementation Address

@dynamic address;

typedef struct Address__storage_ {
  uint32_t _has_storage_[1];
  NSString *address;
} Address__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "address",
        .dataTypeSpecific.className = NULL,
        .number = Address_FieldNumber_Address,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Address__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Address class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Address__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Balance

@implementation Balance

@dynamic amount;
@dynamic pending;

typedef struct Balance__storage_ {
  uint32_t _has_storage_[1];
  int64_t amount;
  int64_t pending;
} Balance__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = Balance_FieldNumber_Amount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Balance__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "pending",
        .dataTypeSpecific.className = NULL,
        .number = Balance_FieldNumber_Pending,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Balance__storage_, pending),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Balance class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Balance__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Wallet

@implementation Wallet

@dynamic pbkdf2Iterations;
@dynamic version;
@dynamic uuid;
@dynamic payLoad;
@dynamic salt;

typedef struct Wallet__storage_ {
  uint32_t _has_storage_[1];
  int32_t pbkdf2Iterations;
  int32_t version;
  NSString *uuid;
  NSString *payLoad;
  NSString *salt;
} Wallet__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pbkdf2Iterations",
        .dataTypeSpecific.className = NULL,
        .number = Wallet_FieldNumber_Pbkdf2Iterations,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Wallet__storage_, pbkdf2Iterations),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = Wallet_FieldNumber_Version,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Wallet__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "uuid",
        .dataTypeSpecific.className = NULL,
        .number = Wallet_FieldNumber_Uuid,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Wallet__storage_, uuid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "payLoad",
        .dataTypeSpecific.className = NULL,
        .number = Wallet_FieldNumber_PayLoad,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Wallet__storage_, payLoad),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "salt",
        .dataTypeSpecific.className = NULL,
        .number = Wallet_FieldNumber_Salt,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Wallet__storage_, salt),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Wallet class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Wallet__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Coin

@implementation Coin

@dynamic status;
@dynamic currency;
@dynamic category;
@dynamic salt;
@dynamic balance;
@dynamic wId;
@dynamic payload;

typedef struct Coin__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  int32_t currency;
  int32_t category;
  NSString *salt;
  NSString *wId;
  NSString *payload;
  int64_t balance;
} Coin__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Coin__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Currency,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Coin__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "category",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Category,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Coin__storage_, category),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "salt",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Salt,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Coin__storage_, salt),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "balance",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Balance,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Coin__storage_, balance),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "wId",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_WId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Coin__storage_, wId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "payload",
        .dataTypeSpecific.className = NULL,
        .number = Coin_FieldNumber_Payload,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(Coin__storage_, payload),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Coin class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Coin__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Coins

@implementation Coins

@dynamic coinsArray, coinsArray_Count;

typedef struct Coins__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *coinsArray;
} Coins__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "coinsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Coin),
        .number = Coins_FieldNumber_CoinsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Coins__storage_, coinsArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Coins class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Coins__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\000Coins\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CoinsDetail

@implementation CoinsDetail

@dynamic hasCoin, coin;
@dynamic coinInfosArray, coinInfosArray_Count;

typedef struct CoinsDetail__storage_ {
  uint32_t _has_storage_[1];
  Coin *coin;
  NSMutableArray *coinInfosArray;
} CoinsDetail__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "coin",
        .dataTypeSpecific.className = GPBStringifySymbol(Coin),
        .number = CoinsDetail_FieldNumber_Coin,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CoinsDetail__storage_, coin),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "coinInfosArray",
        .dataTypeSpecific.className = GPBStringifySymbol(CoinInfo),
        .number = CoinsDetail_FieldNumber_CoinInfosArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(CoinsDetail__storage_, coinInfosArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CoinsDetail class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CoinsDetail__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000coinInfos\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CoinInfo

@implementation CoinInfo

@dynamic index;
@dynamic status;
@dynamic address;
@dynamic label;
@dynamic balance;

typedef struct CoinInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t index;
  int32_t status;
  NSString *address;
  NSString *label;
  int64_t balance;
} CoinInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "index",
        .dataTypeSpecific.className = NULL,
        .number = CoinInfo_FieldNumber_Index,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CoinInfo__storage_, index),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = CoinInfo_FieldNumber_Status,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CoinInfo__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "address",
        .dataTypeSpecific.className = NULL,
        .number = CoinInfo_FieldNumber_Address,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CoinInfo__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "label",
        .dataTypeSpecific.className = NULL,
        .number = CoinInfo_FieldNumber_Label,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CoinInfo__storage_, label),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "balance",
        .dataTypeSpecific.className = NULL,
        .number = CoinInfo_FieldNumber_Balance,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CoinInfo__storage_, balance),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CoinInfo class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CoinInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RespSyncWallet

@implementation RespSyncWallet

@dynamic hasWallet, wallet;
@dynamic status;
@dynamic coinsArray, coinsArray_Count;

typedef struct RespSyncWallet__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  Wallet *wallet;
  NSMutableArray *coinsArray;
} RespSyncWallet__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "wallet",
        .dataTypeSpecific.className = GPBStringifySymbol(Wallet),
        .number = RespSyncWallet_FieldNumber_Wallet,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RespSyncWallet__storage_, wallet),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = RespSyncWallet_FieldNumber_Status,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RespSyncWallet__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "coinsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(CoinsDetail),
        .number = RespSyncWallet_FieldNumber_CoinsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(RespSyncWallet__storage_, coinsArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RespSyncWallet class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RespSyncWallet__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\000Coins\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - LuckyPackageRequest

@implementation LuckyPackageRequest

@dynamic total;
@dynamic amount;
@dynamic fee;
@dynamic allotType;
@dynamic packageType;
@dynamic tips;
@dynamic addressesArray, addressesArray_Count;

typedef struct LuckyPackageRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t total;
  int32_t allotType;
  int32_t packageType;
  NSString *tips;
  NSMutableArray *addressesArray;
  int64_t amount;
  int64_t fee;
} LuckyPackageRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "total",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_Total,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, total),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_Amount,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "fee",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_Fee,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, fee),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "allotType",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_AllotType,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, allotType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "packageType",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_PackageType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, packageType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tips",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_Tips,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, tips),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "addressesArray",
        .dataTypeSpecific.className = NULL,
        .number = LuckyPackageRequest_FieldNumber_AddressesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(LuckyPackageRequest__storage_, addressesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[LuckyPackageRequest class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(LuckyPackageRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransferRequest

@implementation TransferRequest

@dynamic amount;
@dynamic fee;
@dynamic transferType;
@dynamic tips;
@dynamic fromAddressesArray, fromAddressesArray_Count;
@dynamic toAddressesArray, toAddressesArray_Count;

typedef struct TransferRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t transferType;
  NSString *tips;
  NSMutableArray *fromAddressesArray;
  NSMutableArray *toAddressesArray;
  int64_t amount;
  int64_t fee;
} TransferRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_Amount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "fee",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_Fee,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, fee),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "transferType",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_TransferType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, transferType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tips",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_Tips,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, tips),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fromAddressesArray",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_FromAddressesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, fromAddressesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "toAddressesArray",
        .dataTypeSpecific.className = NULL,
        .number = TransferRequest_FieldNumber_ToAddressesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TransferRequest__storage_, toAddressesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransferRequest class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransferRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CrowdfuningRequest

@implementation CrowdfuningRequest

@dynamic amount;
@dynamic total;
@dynamic tips;

typedef struct CrowdfuningRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t total;
  NSString *tips;
  int64_t amount;
} CrowdfuningRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = CrowdfuningRequest_FieldNumber_Amount,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CrowdfuningRequest__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "total",
        .dataTypeSpecific.className = NULL,
        .number = CrowdfuningRequest_FieldNumber_Total,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CrowdfuningRequest__storage_, total),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tips",
        .dataTypeSpecific.className = NULL,
        .number = CrowdfuningRequest_FieldNumber_Tips,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CrowdfuningRequest__storage_, tips),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CrowdfuningRequest class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CrowdfuningRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CrowdfuningResp

@implementation CrowdfuningResp

@dynamic txId;

typedef struct CrowdfuningResp__storage_ {
  uint32_t _has_storage_[1];
  NSString *txId;
} CrowdfuningResp__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "txId",
        .dataTypeSpecific.className = NULL,
        .number = CrowdfuningResp_FieldNumber_TxId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CrowdfuningResp__storage_, txId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CrowdfuningResp class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CrowdfuningResp__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\004\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PayCrowdRequest

@implementation PayCrowdRequest

@dynamic txId;
@dynamic addressesArray, addressesArray_Count;

typedef struct PayCrowdRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *txId;
  NSMutableArray *addressesArray;
} PayCrowdRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "txId",
        .dataTypeSpecific.className = NULL,
        .number = PayCrowdRequest_FieldNumber_TxId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PayCrowdRequest__storage_, txId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "addressesArray",
        .dataTypeSpecific.className = NULL,
        .number = PayCrowdRequest_FieldNumber_AddressesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PayCrowdRequest__storage_, addressesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PayCrowdRequest class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PayCrowdRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\004\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - OriginalTransaction

@implementation OriginalTransaction

@dynamic rawhex;
@dynamic vts;
@dynamic transactionId;

typedef struct OriginalTransaction__storage_ {
  uint32_t _has_storage_[1];
  NSString *rawhex;
  NSString *vts;
  NSString *transactionId;
} OriginalTransaction__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "rawhex",
        .dataTypeSpecific.className = NULL,
        .number = OriginalTransaction_FieldNumber_Rawhex,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(OriginalTransaction__storage_, rawhex),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "vts",
        .dataTypeSpecific.className = NULL,
        .number = OriginalTransaction_FieldNumber_Vts,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(OriginalTransaction__storage_, vts),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "transactionId",
        .dataTypeSpecific.className = NULL,
        .number = OriginalTransaction_FieldNumber_TransactionId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(OriginalTransaction__storage_, transactionId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[OriginalTransaction class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(OriginalTransaction__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PublishTransaction

@implementation PublishTransaction

@dynamic signedHex;
@dynamic transactionId;

typedef struct PublishTransaction__storage_ {
  uint32_t _has_storage_[1];
  NSString *signedHex;
  NSString *transactionId;
} PublishTransaction__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "signedHex",
        .dataTypeSpecific.className = NULL,
        .number = PublishTransaction_FieldNumber_SignedHex,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PublishTransaction__storage_, signedHex),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "transactionId",
        .dataTypeSpecific.className = NULL,
        .number = PublishTransaction_FieldNumber_TransactionId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PublishTransaction__storage_, transactionId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PublishTransaction class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PublishTransaction__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransactionFlowingRequest

@implementation TransactionFlowingRequest

@dynamic currency;

typedef struct TransactionFlowingRequest__storage_ {
  uint32_t _has_storage_[1];
  int32_t currency;
} TransactionFlowingRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowingRequest_FieldNumber_Currency,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransactionFlowingRequest__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransactionFlowingRequest class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransactionFlowingRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransactionFlowing

@implementation TransactionFlowing

@dynamic status;
@dynamic category;
@dynamic amount;
@dynamic time;
@dynamic avatar;
@dynamic username;
@dynamic address;
@dynamic txid;
@dynamic currency;

typedef struct TransactionFlowing__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  int32_t category;
  int32_t currency;
  NSString *avatar;
  NSString *username;
  NSString *address;
  NSString *txid;
  int64_t amount;
  int64_t time;
} TransactionFlowing__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "category",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Category,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, category),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Amount,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "time",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Time,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, time),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Avatar,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, avatar),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "username",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Username,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, username),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "address",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Address,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "txid",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Txid,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, txid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowing_FieldNumber_Currency,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(TransactionFlowing__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransactionFlowing class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransactionFlowing__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - TransactionFlowings

@implementation TransactionFlowings

@dynamic currency;
@dynamic transactionHistoryArray, transactionHistoryArray_Count;

typedef struct TransactionFlowings__storage_ {
  uint32_t _has_storage_[1];
  int32_t currency;
  NSMutableArray *transactionHistoryArray;
} TransactionFlowings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = TransactionFlowings_FieldNumber_Currency,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TransactionFlowings__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "transactionHistoryArray",
        .dataTypeSpecific.className = GPBStringifySymbol(TransactionFlowing),
        .number = TransactionFlowings_FieldNumber_TransactionHistoryArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TransactionFlowings__storage_, transactionHistoryArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TransactionFlowings class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TransactionFlowings__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CreateCoinArgs

@implementation CreateCoinArgs

@dynamic category;
@dynamic currency;
@dynamic salt;
@dynamic masterAddress;
@dynamic payload;
@dynamic wId;

typedef struct CreateCoinArgs__storage_ {
  uint32_t _has_storage_[1];
  int32_t category;
  int32_t currency;
  NSString *salt;
  NSString *masterAddress;
  NSString *payload;
  NSString *wId;
} CreateCoinArgs__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "category",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_Category,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, category),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_Currency,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "salt",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_Salt,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, salt),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "masterAddress",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_MasterAddress,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, masterAddress),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "payload",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_Payload,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, payload),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "wId",
        .dataTypeSpecific.className = NULL,
        .number = CreateCoinArgs_FieldNumber_WId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CreateCoinArgs__storage_, wId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CreateCoinArgs class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CreateCoinArgs__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - RequestCreateCoinInfo

@implementation RequestCreateCoinInfo

@dynamic index;
@dynamic status;
@dynamic address;
@dynamic label;
@dynamic currency;
@dynamic wId;

typedef struct RequestCreateCoinInfo__storage_ {
  uint32_t _has_storage_[1];
  int32_t index;
  int32_t status;
  int32_t currency;
  NSString *address;
  NSString *label;
  NSString *wId;
} RequestCreateCoinInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "index",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_Index,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, index),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_Status,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "address",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_Address,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "label",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_Label,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, label),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "currency",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_Currency,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, currency),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "wId",
        .dataTypeSpecific.className = NULL,
        .number = RequestCreateCoinInfo_FieldNumber_WId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(RequestCreateCoinInfo__storage_, wId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[RequestCreateCoinInfo class]
                                     rootClass:[WalletRoot class]
                                          file:WalletRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(RequestCreateCoinInfo__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
