// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Coin;
@class CoinInfo;
@class Coins;
@class TransactionFlowing;
@class Wallet;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - WalletRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface WalletRoot : GPBRootObject
@end

#pragma mark - RequestWalletInfo

typedef GPB_ENUM(RequestWalletInfo_FieldNumber) {
  RequestWalletInfo_FieldNumber_CheckSum = 1,
  RequestWalletInfo_FieldNumber_Payload = 2,
  RequestWalletInfo_FieldNumber_Salt = 3,
  RequestWalletInfo_FieldNumber_N = 4,
  RequestWalletInfo_FieldNumber_Wid = 5,
  RequestWalletInfo_FieldNumber_Version = 6,
};

/**
 * 新的钱包
 **/
@interface RequestWalletInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *checkSum;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite) int32_t n;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wid;

@property(nonatomic, readwrite) int32_t version;

@end

#pragma mark - RequestUserInfo

typedef GPB_ENUM(RequestUserInfo_FieldNumber) {
  RequestUserInfo_FieldNumber_Uid = 1,
};

@interface RequestUserInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@end

#pragma mark - Address

typedef GPB_ENUM(Address_FieldNumber) {
  Address_FieldNumber_Address = 1,
};

@interface Address : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@end

#pragma mark - Balance

typedef GPB_ENUM(Balance_FieldNumber) {
  Balance_FieldNumber_Amount = 1,
  Balance_FieldNumber_Pending = 2,
};

@interface Balance : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t pending;

@end

#pragma mark - Wallet

typedef GPB_ENUM(Wallet_FieldNumber) {
  Wallet_FieldNumber_Pbkdf2Iterations = 1,
  Wallet_FieldNumber_Version = 2,
  Wallet_FieldNumber_Uuid = 3,
  Wallet_FieldNumber_PayLoad = 4,
  Wallet_FieldNumber_Salt = 5,
};

@interface Wallet : GPBMessage

@property(nonatomic, readwrite) int32_t pbkdf2Iterations;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payLoad;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@end

#pragma mark - Coin

typedef GPB_ENUM(Coin_FieldNumber) {
  Coin_FieldNumber_Status = 1,
  Coin_FieldNumber_Currency = 2,
  Coin_FieldNumber_Category = 3,
  Coin_FieldNumber_Salt = 4,
  Coin_FieldNumber_Balance = 5,
  Coin_FieldNumber_WId = 6,
  Coin_FieldNumber_Payload = 7,
};

@interface Coin : GPBMessage

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite) int64_t balance;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@end

#pragma mark - Coins

typedef GPB_ENUM(Coins_FieldNumber) {
  Coins_FieldNumber_CoinsArray = 1,
};

@interface Coins : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Coin*> *coinsArray;
/** The number of items in @c coinsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger coinsArray_Count;

@end

#pragma mark - CoinsDetail

typedef GPB_ENUM(CoinsDetail_FieldNumber) {
  CoinsDetail_FieldNumber_Coin = 1,
  CoinsDetail_FieldNumber_CoinInfosArray = 2,
};

@interface CoinsDetail : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Coin *coin;
/** Test to see if @c coin has been set. */
@property(nonatomic, readwrite) BOOL hasCoin;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CoinInfo*> *coinInfosArray;
/** The number of items in @c coinInfosArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger coinInfosArray_Count;

@end

#pragma mark - CoinInfo

typedef GPB_ENUM(CoinInfo_FieldNumber) {
  CoinInfo_FieldNumber_Index = 1,
  CoinInfo_FieldNumber_Status = 2,
  CoinInfo_FieldNumber_Address = 3,
  CoinInfo_FieldNumber_Label = 4,
  CoinInfo_FieldNumber_Balance = 5,
};

@interface CoinInfo : GPBMessage

@property(nonatomic, readwrite) int32_t index;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@property(nonatomic, readwrite) int64_t balance;

@end

#pragma mark - RespSyncWallet

typedef GPB_ENUM(RespSyncWallet_FieldNumber) {
  RespSyncWallet_FieldNumber_Wallet = 1,
  RespSyncWallet_FieldNumber_Status = 2,
  RespSyncWallet_FieldNumber_Coins = 3,
};

@interface RespSyncWallet : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Wallet *wallet;
/** Test to see if @c wallet has been set. */
@property(nonatomic, readwrite) BOOL hasWallet;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite, strong, null_resettable) Coins *coins;
/** Test to see if @c coins has been set. */
@property(nonatomic, readwrite) BOOL hasCoins;

@end

#pragma mark - LuckyPackageRequest

typedef GPB_ENUM(LuckyPackageRequest_FieldNumber) {
  LuckyPackageRequest_FieldNumber_Total = 1,
  LuckyPackageRequest_FieldNumber_Amount = 2,
  LuckyPackageRequest_FieldNumber_Fee = 3,
  LuckyPackageRequest_FieldNumber_AllotType = 4,
  LuckyPackageRequest_FieldNumber_PackageType = 5,
  LuckyPackageRequest_FieldNumber_Tips = 6,
  LuckyPackageRequest_FieldNumber_AddressesArray = 7,
};

@interface LuckyPackageRequest : GPBMessage

@property(nonatomic, readwrite) int32_t total;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t fee;

@property(nonatomic, readwrite) int32_t allotType;

@property(nonatomic, readwrite) int32_t packageType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *addressesArray;
/** The number of items in @c addressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addressesArray_Count;

@end

#pragma mark - TransferRequest

typedef GPB_ENUM(TransferRequest_FieldNumber) {
  TransferRequest_FieldNumber_Amount = 1,
  TransferRequest_FieldNumber_Fee = 2,
  TransferRequest_FieldNumber_TransferType = 3,
  TransferRequest_FieldNumber_Tips = 4,
  TransferRequest_FieldNumber_FromAddressesArray = 5,
  TransferRequest_FieldNumber_ToAddressesArray = 6,
};

@interface TransferRequest : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t fee;

@property(nonatomic, readwrite) int32_t transferType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *fromAddressesArray;
/** The number of items in @c fromAddressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fromAddressesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *toAddressesArray;
/** The number of items in @c toAddressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger toAddressesArray_Count;

@end

#pragma mark - CrowdfuningRequest

typedef GPB_ENUM(CrowdfuningRequest_FieldNumber) {
  CrowdfuningRequest_FieldNumber_Amount = 1,
  CrowdfuningRequest_FieldNumber_Total = 2,
  CrowdfuningRequest_FieldNumber_Tips = 3,
};

@interface CrowdfuningRequest : GPBMessage

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int32_t total;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tips;

@end

#pragma mark - CrowdfuningResp

typedef GPB_ENUM(CrowdfuningResp_FieldNumber) {
  CrowdfuningResp_FieldNumber_TxId = 1,
};

@interface CrowdfuningResp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *txId;

@end

#pragma mark - PayCrowdRequest

typedef GPB_ENUM(PayCrowdRequest_FieldNumber) {
  PayCrowdRequest_FieldNumber_TxId = 1,
  PayCrowdRequest_FieldNumber_AddressesArray = 2,
};

@interface PayCrowdRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *txId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *addressesArray;
/** The number of items in @c addressesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addressesArray_Count;

@end

#pragma mark - OriginalTransaction

typedef GPB_ENUM(OriginalTransaction_FieldNumber) {
  OriginalTransaction_FieldNumber_Rawhex = 1,
  OriginalTransaction_FieldNumber_Vts = 2,
  OriginalTransaction_FieldNumber_TransactionId = 3,
};

@interface OriginalTransaction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *rawhex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *vts;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - PublishTransaction

typedef GPB_ENUM(PublishTransaction_FieldNumber) {
  PublishTransaction_FieldNumber_SignedHex = 1,
  PublishTransaction_FieldNumber_TransactionId = 2,
};

@interface PublishTransaction : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *signedHex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionId;

@end

#pragma mark - TransactionFlowingRequest

typedef GPB_ENUM(TransactionFlowingRequest_FieldNumber) {
  TransactionFlowingRequest_FieldNumber_Currency = 1,
};

@interface TransactionFlowingRequest : GPBMessage

@property(nonatomic, readwrite) int32_t currency;

@end

#pragma mark - TransactionFlowing

typedef GPB_ENUM(TransactionFlowing_FieldNumber) {
  TransactionFlowing_FieldNumber_Status = 1,
  TransactionFlowing_FieldNumber_Category = 2,
  TransactionFlowing_FieldNumber_Amount = 3,
  TransactionFlowing_FieldNumber_Time = 4,
  TransactionFlowing_FieldNumber_Avatar = 5,
  TransactionFlowing_FieldNumber_Username = 6,
  TransactionFlowing_FieldNumber_Address = 7,
  TransactionFlowing_FieldNumber_Txid = 8,
  TransactionFlowing_FieldNumber_Currency = 9,
};

@interface TransactionFlowing : GPBMessage

/** confirm unconfirm */
@property(nonatomic, readwrite) int32_t status;

/** transfer luckypackage */
@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite) int64_t amount;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@property(nonatomic, readwrite, copy, null_resettable) NSString *txid;

/** btc ltc */
@property(nonatomic, readwrite) int32_t currency;

@end

#pragma mark - TransactionFlowings

typedef GPB_ENUM(TransactionFlowings_FieldNumber) {
  TransactionFlowings_FieldNumber_Currency = 1,
  TransactionFlowings_FieldNumber_TransactionHistoryArray = 2,
};

@interface TransactionFlowings : GPBMessage

/** btc ltc */
@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TransactionFlowing*> *transactionHistoryArray;
/** The number of items in @c transactionHistoryArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger transactionHistoryArray_Count;

@end

#pragma mark - CreateCoinArgs

typedef GPB_ENUM(CreateCoinArgs_FieldNumber) {
  CreateCoinArgs_FieldNumber_Category = 1,
  CreateCoinArgs_FieldNumber_Currency = 2,
  CreateCoinArgs_FieldNumber_Salt = 3,
  CreateCoinArgs_FieldNumber_MasterAddress = 4,
  CreateCoinArgs_FieldNumber_Payload = 5,
  CreateCoinArgs_FieldNumber_WId = 6,
};

@interface CreateCoinArgs : GPBMessage

@property(nonatomic, readwrite) int32_t category;

@property(nonatomic, readwrite) int32_t currency;

@property(nonatomic, readwrite, copy, null_resettable) NSString *salt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *masterAddress;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
